# This configuration file is created to run on Gitpod.
# Please adjust to your needs (see https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml)
# and commit this file to your remote git repository to share the goodness with others.

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

tasks:
  - name: Install Java 21 and set as default
    init: |
      sdk install java 21.0.2-tem
      sdk default java 21.0.2-tem

  - name: Build the Dependencies and Start the docker containers
    depends_on:
      - Install Java 21 and set as default
    init: |
      cd dataexport && mvn clean install && cd .. && mvn celan install -DskipTests && cd frontend && npm install && cd ..
    command:  |
      docker-compose -f dev.docker-compose.yml up -d   

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-pack
 


