# This configuration file is created to run on Gitpod.
# Please adjust to your needs (see https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml)
# and commit this file to your remote git repository to share the goodness with others.

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

tasks:
  Java_Setup:
    name: "Install Java 21 and set as default"
    init: |
      sdk install java 21.0.2-tem
      sdk default java 21.0.2-tem

  Buld_And_Run:
    name: "Build the Dependencies and Run the docker containers"
    dependsOn: ['Java_Setup']
    init: |
      cd dataexport
      mvn clean install
      cd ..
      mvn clean install -DskipTests
      cd frontend
      npm install
      cd ..
    command: |
      docker-compose -f dev.docker-compose.yml up -d

vscode:
  extensions: ['redhat.java' ,'vscjava.vscode-java-pack']
 


